version: '3.8'

services:
  app:
    build: .
    image: kube-ops:local
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///app.db
    command: ["gunicorn", "-w", "2", "-b", ":8000", "app:app"]
    restart: unless-stopped
