replicas: 1
minimumMasterNodes: 1
esConfig:
  elasticsearch.yml: |
    xpack.security.enabled: false
resources:
  requests:
    cpu: 200m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 2Gi
volumeClaimTemplate:
  resources:
    requests:
      storage: 3Gi
