version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 20s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    build:
      context: ./filebeat
    image: local/filebeat:8.13.4
    container_name: filebeat
    user: root
    volumes:
      - app_logs:/var/log/app:ro
    depends_on:
      elasticsearch:
        condition: service_healthy

  app:
    build:
      context: ..
    image: kube-ops:compose
    container_name: kube_ops_app
    environment:
      - PORT=8000
    ports:
      - "8000:8000"
    volumes:
      - app_logs:/var/log/app
    labels: []
    depends_on:
      - filebeat
volumes:
  app_logs:
