filebeat.inputs:
  - type: filestream
    id: app-log
    paths:
      - /var/log/app/*.log
    # Use Elasticsearch data streams for custom logs: logs-<dataset>-<namespace>
    data_stream:
      dataset: app
      namespace: default
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: "app"
          overwrite_keys: false
          add_error_key: true
      - add_fields:
          target: ''
          fields:
            app: kube-ops

processors:
  - add_docker_metadata: ~

setup.template.enabled: true
setup.kibana:
  host: kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: http
  # Explicitly use data streams (default in 8.x). Index will be logs-<dataset>-<namespace>.
  indices: []

logging.level: info
logging.to_files: false
logging.to_stdout: true
strict.perms: false