filebeat.inputs:
  - type: filestream
    id: docker-logs
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - decode_json_fields:
          fields: ["message"]
          target: ""
          overwrite_keys: true
          add_error_key: true
      - add_fields:
          target: ''
          fields:
            app: kube-ops

processors:
  - add_docker_metadata: ~

setup.template.enabled: true
setup.kibana:
  host: kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: http

logging.level: info
logging.to_files: false
logging.to_stdout: true
strict.perms: false