filebeat.inputs:
  - type: filestream
    id: app-log
    paths:
      - /var/log/app/*.log
    data_stream:
      dataset: app
      namespace: default
    parsers:
      - ndjson:
          target: ""            # coloca cada chave do JSON na raiz
          overwrite_keys: true
          add_error_key: true
    processors:
      - add_fields:
          target: ''
          fields:
            app: kube-ops

processors:
  - add_docker_metadata: ~

setup.template.enabled: true
setup.kibana:
  host: kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: http
  indices: []

logging.level: debug
logging.selectors: ["elasticsearch","publish"]
logging.to_files: false
logging.to_stdout: true
strict.perms: false