filebeat.inputs:
  - type: filestream
    id: app-log
    enabled: true
    paths:
      - /var/log/app/*.log
    # Envia todas as linhas; decodifica JSON apenas quando a linha começa com '{'
    processors: []

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
      add_error_key: true
      when:
        regexp:
          message: '^\{'
  - add_fields:
      target: ''
      fields:
        service.name: kube-ops
  - add_docker_metadata: ~

# Desabilita ILM e gerenciamento automático de template (índice será criado dinamicamente)
setup.ilm.enabled: false
setup.template.enabled: false

setup.kibana:
  host: kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  protocol: http
  index: "app-logs-%{+yyyy.MM.dd}"
  data_streams.enabled: false

logging.level: info
logging.to_files: false
logging.to_stdout: true
strict.perms: false